[desc="Cross Origin Resource Sharing (CORS) issues."]
= The "mode" option on Fetch

Per March 2023 it became clear that the PDR suffered from an intermittent CORS problem. For no apparant reason, requests to perspectives.domains would be rejected. 

At first it seemed to be an Apache problem. This is because the Chrome browser would report that the wrong certificate was sent along with a file requested from this domain (the inplace.dev certificate seemed to be attached).
However, I've come to believe that Apache is not the source of the problem.
Rather, the mistake stems from the fetch request made by Pouchdb: this does not set the "mode" option, making it effectively "no-cors" where it should have been "cors". According to the spec:

	A request has an associated mode, which is "same-origin", "cors", "no-cors", "navigate", 
	or "websocket". Unless stated otherwise, it is "no-cors".
	(https://fetch.spec.whatwg.org/)

I have corrected this by using the 'fetch' option provided to the database creation of Pouchdb. It allows one to capture fetch and add options and headers etc. to the actual request. On the assumption that, for Perspectives, any request through Pouchdb will be a cors request because we don't store resources on mycontexts.com, every request is a cors request.

It seems as though FireFox doesn't suffer from the same problem. This might be because browser implementers have a certain freedom in implementing a default for the "mode" option:

	Even though the default request mode is "no-cors", standards are highly discouraged from using it for 
	new features. It is rather unsafe.
	(https://fetch.spec.whatwg.org/)

It looks like Chrome defaults to "no-cors" and Firefox does not.

== AffJax
Affjax uses XmlHttpRequests. Some points to notice:
* withCredentials should be set to false
* when content-type is Application/Json, this causes the SharedWorker context to consider it a CORS request. 
* Consequently, the server should respond with a header Access-Control-Allow-Origin that includes the origin of the request. C.q. https://mycontexts.com (no trailing slash).
* In the Apache configuration, when handling an OPTIONS to return no response, we should use the 'always' keyword to make sure the header is sent even when the response is empty.
* Apache doesn't send headers in sections in which we configure Apache to handle OPTIONS with SetHandler or rewriting. Hence we should send the headers not in e.g. a Location section where we handle OPTIONS in this way, but in the main Virtual host.