[desc="An introduction to this documentation"]
== Introduction to the docs

:url-nlnet: https://nlnet.nl/project/InPlace/index.html
:url-perspectivesdoc: https://joopringelberg.github.io/perspectives-documentation/
:url-inplaceuserguide: https://joopringelberg.github.io/perspectives-documentation/userguide.html
:url-inplaceissues: https://github.com/joopringelberg/inplace/issues
:url-reference: https://joopringelberg.github.io/perspectives-documentation/perspectives%20language%20reference.html
:url-tutorial: https://mycontexts.com/gettingstarted/overview.html

This documentation grew out of some 50 design documents written over the course of the years from 2016 to 2022. They were first integrated into this single document in oktober 2022, made possible by a grant from the NGI ZERO Search program through the {url-nlnet}[NLnet] organization.

From that date on, the individual design documents are no longer updated: just this (online) documentation is.

NOTE: This documentation is a work in progress! If you think a topic is missing, please create an {url-inplaceissues}[issue here].

=== Organization of this document
This document is organized into three parts.

PART I gives a high level overview of the Perspectives Distributed Runtime. It is organised around a functional decomposition of the Perspectives Distributed Runtime into four parts:

* The parser / compiler
* The Functional Reactive Pattern (FRP)
* State change through assignment
* Synchronization
//* Caching
//* User interface generation

PART II is devoted to the _design_ of the Perspectives Language. It ranges from high level conceptual overviews - such as the _type system_ - to implementation details. The topics covered are:

* The type system
* Identifiers and variables
* Perspectives
* Queries
* Aspects
* Model source texts

PART III goes into the nitty-gritty of the implementation. Expect the most technical issues here. We cover:

* The architecture of the PDR and MyContexts
* The mechanisms of state change
* The workings of state synchronization between peers
* The Foreign Function Interface (FFI)

PART IV discusses a number of models that are essential to the functioning of MyContexts, such as:

* model://perspectives.domains#System
* model://perspectives.domains#CouchdbManagement

=== Other resources
There are quite a few other resources on the Perspectives project.

* The starting page for all https://joopringelberg.github.io/perspectives-documentation/[Perspectives documentation].

* The https://joopringelberg.github.io/perspectives-documentation/userguide.html[MyContexts User Guide], which is more of a reference.

* https://mycontexts.com/gettingstarted/overview.html[A small tutorial] to get started.

* https://joopringelberg.github.io/perspectives-documentation/perspectives%20language%20reference.html[Reference of the Perspectives Language]

NOTE: If you find something wrong with this documentation, please create an issue at the {url-inplaceissues}[Issues section on Github]. Use the label `documentation`.